import {
  Activity,
  Apple,
  Battery,
  Bell,
  BookOpen,
  Briefcase,
  Building,
  Calendar,
  Clock,
  Cpu,
  Database,
  Droplet,
  Fingerprint,
  Flag,
  Footprints,
  Globe,
  Heart,
  Key,
  Megaphone,
  MessageCircle,
  Moon,
  Palette,
  Phone,
  Plug,
  Rocket,
  Scale,
  Server,
  Shield,
  Sprout,
  Sunrise,
  Syringe,
  TriangleAlert,
  Users,
  Wrench,
  type IconNode,
} from 'lucide';

export interface LucideIcon {
  id: string;
  name: string;
  icon: IconNode;
}

const icon = (name: string, node: IconNode): LucideIcon => ({ id: `lucide:${name}`, name, icon: node });

export const LUCIDE_ICONS: readonly LucideIcon[] = [
  icon('database', Database),
  icon('fingerprint', Fingerprint),
  icon('server', Server),
  icon('syringe', Syringe),
  icon('sprout', Sprout),
  icon('scale', Scale),
  icon('battery', Battery),
  icon('flag', Flag),
  icon('book-open', BookOpen),
  icon('megaphone', Megaphone),
  icon('rocket', Rocket),
  icon('cpu', Cpu),
  icon('clock', Clock),
  icon('calendar', Calendar),
  icon('heart', Heart),
  icon('key', Key),
  icon('phone', Phone),
  icon('bell', Bell),
  icon('activity', Activity),
  icon('droplet', Droplet),
  icon('shield', Shield),
  icon('users', Users),
  icon('plug', Plug),
  icon('globe', Globe),
  icon('moon', Moon),
  icon('sunrise', Sunrise),
  icon('footprints', Footprints),
  icon('apple', Apple),
  icon('wrench', Wrench),
  icon('briefcase', Briefcase),
  icon('palette', Palette),
  icon('building', Building),
  icon('message-circle', MessageCircle),
  icon('triangle-alert', TriangleAlert),
];